#!/bin/bash

CLIENT_DIR="$HOME/.rd-docker"
CLIENT_PATH="$CLIENT_DIR/rd-docker-cli"
REPOSITORY="https://github.com/ResultadosDigitais/rd-docker.git"

clone_repository() {
  git clone "$REPOSITORY" "$CLIENT_DIR"
}

if [[ ! -d "$CLIENT_DIR" ]]; then
  clone_repository
fi

$CLIENT_PATH $@
